-- File: decodificador_7seg.vhd
-- Generated by MyHDL 0.11.52
-- Date:    Sun Oct  4 22:48:31 2026 UTC


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity decodificador_7seg is
    port (
        entrada: in unsigned(3 downto 0);
        salida_segmentos: out unsigned(6 downto 0)
    );
end entity decodificador_7seg;
-- Módulo combinacional del decodificador.

architecture MyHDL of decodificador_7seg is




begin




logica_combinacional: process (entrada) is
begin
    case to_integer(entrada) is
        when 0 => salida_segmentos <= "1111110";
        when 1 => salida_segmentos <= "0110000";
        when 2 => salida_segmentos <= "1101101";
        when 3 => salida_segmentos <= "1111001";
        when 4 => salida_segmentos <= "0110011";
        when 5 => salida_segmentos <= "1011011";
        when 6 => salida_segmentos <= "1011111";
        when 7 => salida_segmentos <= "1110000";
        when 8 => salida_segmentos <= "1111111";
        when 9 => salida_segmentos <= "1111011";
        when 10 => salida_segmentos <= "0000001";
        when 11 => salida_segmentos <= "0110110";
        when 12 => salida_segmentos <= "1100011";
        when 13 => salida_segmentos <= "0011101";
        when 14 => salida_segmentos <= "1001001";
        when others => salida_segmentos <= "0011100";
    end case;
end process logica_combinacional;

end architecture MyHDL;
